# Inspect test-run output — CAM & CLM variable tables

Tabulates the variables actually written by the production `h0` tapes (one CAM test, one CLM test),
and checks the **requested whitelist vs what actually landed** in the file.

Outputs per model: `vars_<model>.csv` and a printed present / missing / unexpected report.

## 1 · Configuration — point at your two test files

In [5]:
from pathlib import Path
import glob

dir_path = "/cluster/work/users/adelez/archive/NF2000norbc_tropstratchem_nudg_ctrl_f19_f19-test-new-diagnostics"
CAM_GLOB = dir_path + "/atm/hist/*cam.h0*.nc"
CLM_GLOB = dir_path + "/lnd/hist/*clm2.h0*.nc"

OUT_DIR = Path("check_output"); OUT_DIR.mkdir(exist_ok=True)
RECORDS_PER_MEMBER = 120   # 10 yr monthly, for size projection

def first_match(pat):
    hits = sorted(glob.glob(pat, recursive=True))
    if not hits: print(f"[!] no file matched {pat}"); return None
    if len(hits) > 1: print(f"[i] {len(hits)} matched {pat}; using {hits[0]}")
    return hits[0]

CAM_FILE = first_match(CAM_GLOB)
CLM_FILE = first_match(CLM_GLOB)
print("CAM:", CAM_FILE); print("CLM:", CLM_FILE)

[i] 2 matched /cluster/work/users/adelez/archive/NF2000norbc_tropstratchem_nudg_ctrl_f19_f19-test-new-diagnostics/atm/hist/*cam.h0*.nc; using /cluster/work/users/adelez/archive/NF2000norbc_tropstratchem_nudg_ctrl_f19_f19-test-new-diagnostics/atm/hist/NF2000norbc_tropstratchem_nudg_ctrl_f19_f19-test-new-diagnostics.cam.h0.2000-01-01-00000.nc
[i] 2 matched /cluster/work/users/adelez/archive/NF2000norbc_tropstratchem_nudg_ctrl_f19_f19-test-new-diagnostics/lnd/hist/*clm2.h0*.nc; using /cluster/work/users/adelez/archive/NF2000norbc_tropstratchem_nudg_ctrl_f19_f19-test-new-diagnostics/lnd/hist/NF2000norbc_tropstratchem_nudg_ctrl_f19_f19-test-new-diagnostics.clm2.h0.2000-01-01-00000.nc
CAM: /cluster/work/users/adelez/archive/NF2000norbc_tropstratchem_nudg_ctrl_f19_f19-test-new-diagnostics/atm/hist/NF2000norbc_tropstratchem_nudg_ctrl_f19_f19-test-new-diagnostics.cam.h0.2000-01-01-00000.nc
CLM: /cluster/work/users/adelez/archive/NF2000norbc_tropstratchem_nudg_ctrl_f19_f19-test-new-diagnostics/lnd/hist/NF2000norbc_tropstratchem_nudg_ctrl_f19_f19-test-new-diagnostics.clm2.h0.2000-01-01-00000.nc

## 2 · Functions (metadata-only) + the whitelist branch maps

In [6]:
import numpy as np, pandas as pd, xarray as xr

# dims that are NOT an extra (vertical / pft / column) level:
FLAT_DIMS = {"time","lat","lon","lonu","latu","nbnd","hist_interval","chars","string_length"}

def build_var_table(path):
    """One row per data variable. Lazy open, metadata only — no data is read."""
    ds = xr.open_dataset(path, decode_times=False, decode_cf=False)
    rows=[]
    for name, da in ds.data_vars.items():
        dims=tuple(da.dims); sizes={d:ds.sizes[d] for d in dims}
        extra=[d for d in dims if d not in FLAT_DIMS]           # vertical/pft/etc.
        nontime=[sizes[d] for d in dims if d!="time"]
        per=(int(np.prod(nontime)) if nontime else 1)*da.dtype.itemsize
        rows.append(dict(variable=name, dims=",".join(dims),
            multilevel=bool(extra), level_dim=",".join(extra),
            dtype=str(da.dtype), shape=",".join(str(sizes[d]) for d in dims),
            mib_per_rec=per/1024**2,
            units=da.attrs.get("units",""), long_name=da.attrs.get("long_name","")))
    ds.close()
    return pd.DataFrame(rows).sort_values("variable").reset_index(drop=True)

def tag_and_report(df, branches, model, records=RECORDS_PER_MEMBER):
    """Add a 'branch' column, write CSV, print counts + present/missing/unexpected."""
    v2b = {v:b for b,vs in branches.items() for v in vs}
    df = df.copy()
    df["branch"] = df.variable.map(v2b).fillna("(unexpected)")
    df.to_csv(OUT_DIR/f"vars_{model}.csv", index=False)

    gib = lambda s: s*records/1024
    present = set(df.variable)
    requested = set(v2b)
    missing = sorted(requested - present)          # asked for, not in file
    unexpected = sorted(df.loc[df.branch=="(unexpected)","variable"])  # in file, not requested

    print(f"===== {model.upper()} : {CAM_FILE if model=='cam' else CLM_FILE} =====")
    print(f"variables in file : {len(df)}  (multilevel={int(df.multilevel.sum())}, "
          f"2D={int((~df.multilevel).sum())})")
    print(f"projected size    : ~{gib(df.mib_per_rec.sum()):.2f} GiB/member (uncompressed, {records} recs)")
    print("\nby branch (count | GiB/member):")
    g=(df.assign(g=lambda d:gib(d.mib_per_rec)).groupby("branch")
         .agg(n=("variable","size"), gib=("g","sum")).sort_values("gib",ascending=False))
    print(g.to_string())
    print(f"\nMISSING (requested but absent): {len(missing)}")
    if missing: print("  ", missing)
    print(f"UNEXPECTED (in file, not requested): {len(unexpected)}")
    if unexpected: print("  ", unexpected)
    return df

# ---- whitelist branch maps (from production_diagnostics / clm_diagnostics) ----
CAM_BRANCHES = {
 "radiative": "FSNT FSNTC FLNT FLNTC FLUT FLUTC FSNTOA FSNTOAC SOLIN FSNS FSNSC FLNS FLNSC FSDS FSDSC FLDS SWCF LWCF".split(),
 "ghan_drf": "FSNT_DRF FLNT_DRF FSNTCDRF FLNTCDRF FSDS_DRF FSDSCDRF FSUTADRF FSUS_DRF FLUS".split(),
 "bvoc": "SFISOP SFMTERP SFBCARY cb_ISOP cb_MTERP cb_BCARY MEG_ISOP MEG_MTERP MEG_BCARY emis_ISOP emis_MTERP ISOP MTERP BCARY".split(),
 "soa_core": "SOA_LV SOA_SV H2SO4 SOA_NA SOA_A1 SO4_NA SO4_A1 N_AER cb_SOA_LV cb_SOA_SV cb_H2SO4".split(),
 "npf": "NUCLRATE FORMRATE COAGNUCL GR GRH2SO4 GRSOA ORGNUCL NUCLSOA".split(),
 "tendencies": "SOA_NAcondTend SOA_A1condTend SOA_NAcoagTend SOA_A1coagTend SOA_NA_mixnuc1 SOA_A1_mixnuc1 SO4_NAcondTend SO4_A1condTend SO4_NAcoagTend SO4_A1coagTend SO4_NA_mixnuc1 SO4_A1_mixnuc1".split(),
 "deposition": "SOA_NADDF SOA_A1DDF SO4_NADDF SO4_A1DDF DF_H2SO4 SOA_NASFWET SOA_A1SFWET SO4_NASFWET SO4_A1SFWET WD_A_H2SO4 WD_H2SO4".split(),
 "ccn": "CCN1 CCN2 CCN3 CCN4 CCN5 CCN6 CCN7 CCN_B".split(),
 "optics": "AOD_VIS AEROD_v DOD550 DOD440 DOD870 ABS550 ABS550_A OD550DRY AB550DRY CABS550 A550_BC A550_POM A550_SO4 A550_SS A550_DU".split(),
 "cloud": "CDNUMC TGCLDLWP TGCLDIWP TGCLDCWP CLDTOT CLDLOW CLDMED CLDHGH ACTREL ACTREI ACTNL FCTL FCTI CLOUD CLDLIQ CLDICE AREL AREI AWNC FREQL FREQI NUMLIQ NUMICE".split(),
 "biogeophysical": "TS TREFHT SHFLX LHFLX PRECC PRECL PRECSC PRECSL TAUX TAUY PSL U10 QREFHT LANDFRAC OCNFRAC ICEFRAC SNOWHLND".split(),
 "ch4_ozone": "O3 OH CH4 NO NO2 CO HO2 TROP_P TROP_T TROP_Z".split(),
 "meteorology": "T Q U V OMEGA Z3 PS".split(),
}
CLM_BRANCHES = {
 "radiation_albedo": "FSA FSR FIRA FIRE FSH EFLX_LH_TOT FGR FSDS FLDS FSDSVD FSDSVI FSDSND FSDSNI FSRVD FSRND".split(),
 "snow": "H2OSNO SNOWDP FSNO SNOWLIQ SNOWICE".split(),
 "temperature": "TSA TV TG TSKIN TSOI".split(),
 "vegetation": "TLAI ELAI LAISUN LAISHA TSAI HTOP".split(),
 "megan_drivers": "PARVEGLN BTRANMN".split(),
 "hydrology_et": "QFLX_EVAP_TOT QSOIL QVEGE QVEGT QINTR QOVER QRUNOFF RAIN SNOW H2OSOI SOILLIQ SOILICE ZWT".split(),
 "carbon": "GPP NPP AR HR NEE".split(),
 "other": "WIND PCT_NAT_PFT".split(),
 "megan_emissions": ("MEG_isoprene MEG_carene_3 MEG_limonene MEG_myrcene MEG_pinene_a MEG_pinene_b "
                     "MEG_acetaldehyde MEG_acetic_acid MEG_acetone MEG_ethanol MEG_formaldehyde MEG_methanol").split(),
 "megan_gamma": ("GAMMAL GAMMAS GAMMAC_isoprene "
                 "EPS_isoprene GAMMA_isoprene GAMMAP_isoprene GAMMAT_isoprene GAMMAA_isoprene "
                 "EPS_pinene_a GAMMA_pinene_a GAMMAP_pinene_a GAMMAT_pinene_a GAMMAA_pinene_a "
                 "EPS_carene_3 GAMMA_carene_3 GAMMAP_carene_3 GAMMAT_carene_3 GAMMAA_carene_3 "
                 "EPS_pinene_b GAMMA_pinene_b GAMMAP_pinene_b GAMMAT_pinene_b GAMMAA_pinene_b "
                 "EPS_myrcene GAMMA_myrcene GAMMAP_myrcene GAMMAT_myrcene GAMMAA_myrcene "
                 "EPS_limonene GAMMA_limonene GAMMAP_limonene GAMMAT_limonene GAMMAA_limonene").split(),
}

## 3 · CAM test file

In [7]:
cam = tag_and_report(build_var_table(CAM_FILE), CAM_BRANCHES, "cam") if CAM_FILE else None
cam.head(20) if cam is not None else None

===== CAM : /cluster/work/users/adelez/archive/NF2000norbc_tropstratchem_nudg_ctrl_f19_f19-test-new-diagnostics/atm/hist/NF2000norbc_tropstratchem_nudg_ctrl_f19_f19-test-new-diagnostics.cam.h0.2000-01-01-00000.nc =====
variables in file : 188  (multilevel=54, 2D=134)
projected size    : ~10.59 GiB/member (uncompressed, 120 recs)

by branch (count | GiB/member):
                 n       gib
branch
cloud           23  2.057877
soa_core        11  1.600571
npf              8  1.582031
ch4_ozone       10  1.402817
ccn              8  1.390457
meteorology      7  1.192703
bvoc            14  0.661240
optics          15  0.284271
radiative       18  0.111237
biogeophysical  17  0.105057
tendencies      12  0.074158
deposition      11  0.067978
ghan_drf         9  0.055618
(unexpected)    25  0.000216

MISSING (requested but absent): 0
UNEXPECTED (in file, not requested): 25
   ['P0', 'ch4vmr', 'co2vmr', 'date', 'date_written', 'datesec', 'f11vmr', 'f12vmr', 'gw', 'hyai', 'hyam', 'hybi', 'hybm', 'mdt', 'n2ovmr', 'nbdate', 'nbsec', 'ndbase', 'ndcur', 'nsbase', 'nscur', 'nsteph', 'sol_tsi', 'time_bnds', 'time_written']

,variable,dims,multilevel,level_dim,dtype,shape,mib_per_rec,units,long_name,branch
0,A550_BC,"time,lat,lon",False,,float32,"1,96,144",0.052734,unitless,BC abs. aerosol optical depth 550nm,optics
1,A550_DU,"time,lat,lon",False,,float32,"1,96,144",0.052734,unitless,mineral abs. aerosol optical depth 550nm,optics
2,A550_POM,"time,lat,lon",False,,float32,"1,96,144",0.052734,unitless,OC abs. aerosol optical depth 550nm,optics
3,A550_SO4,"time,lat,lon",False,,float32,"1,96,144",0.052734,unitless,SO4 aerosol abs. optical depth 550nm,optics
4,A550_SS,"time,lat,lon",False,,float32,"1,96,144",0.052734,unitless,sea-salt abs aerosol optical depth 550nm,optics
5,AB550DRY,"time,lat,lon",False,,float32,"1,96,144",0.052734,unitless,Dry aerosol absorptive optical depth at 550nm,optics
6,ABS550,"time,lat,lon",False,,float32,"1,96,144",0.052734,unitless,Aerosol absorptive optical depth at 550nm,optics
7,ABS550_A,"time,lev,lat,lon",True,lev,float32,"1,32,96,144",1.687500,m-1,aerosol absorption coefficient,optics
8,ACTNL,"time,lat,lon",False,,float32,"1,96,144",0.052734,m-3,Average Cloud Top droplet number,cloud
9,ACTREI,"time,lat,lon",False,,float32,"1,96,144",0.052734,Micron,Average Cloud Top ice effective radius,cloud
10,ACTREL,"time,lat,lon",False,,float32,"1,96,144",0.052734,Micron,Average Cloud Top droplet effective radius,cloud
11,AEROD_v,"time,lat,lon",False,,float32,"1,96,144",0.052734,1,Total Aerosol Optical Depth in visible band,optics
12,AOD_VIS,"time,lat,lon",False,,float32,"1,96,144",0.052734,unitless,Aerosol optical depth at 0.442-0.625um,optics
13,AREI,"time,lev,lat,lon",True,lev,float32,"1,32,96,144",1.687500,Micron,Average ice effective radius,cloud
14,AREL,"time,lev,lat,lon",True,lev,float32,"1,32,96,144",1.687500,Micron,Average droplet effective radius,cloud
15,AWNC,"time,lev,lat,lon",True,lev,float32,"1,32,96,144",1.687500,m-3,Average cloud water number conc,cloud
16,BCARY,"time,lev,lat,lon",True,lev,float32,"1,32,96,144",1.687500,mol/mol,BCARY concentration,bvoc
17,CABS550,"time,lat,lon",False,,float32,"1,96,144",0.052734,unitless,Clear air Aerosol abs optical depth at 550nm,optics
18,CCN1,"time,lev,lat,lon",True,lev,float32,"1,32,96,144",1.687500,#/cm3,CCN concentration at S=0.02%,ccn
19,CCN2,"time,lev,lat,lon",True,lev,float32,"1,32,96,144",1.687500,#/cm3,CCN concentration at S=0.05%,ccn

## 4 · CLM test file

In [8]:
clm = tag_and_report(build_var_table(CLM_FILE), CLM_BRANCHES, "clm") if CLM_FILE else None
clm.head(20) if clm is not None else None

===== CLM : /cluster/work/users/adelez/archive/NF2000norbc_tropstratchem_nudg_ctrl_f19_f19-test-new-diagnostics/lnd/hist/NF2000norbc_tropstratchem_nudg_ctrl_f19_f19-test-new-diagnostics.clm2.h0.2000-01-01-00000.nc =====
variables in file : 555  (multilevel=43, 2D=512)
projected size    : ~17.48 GiB/member (uncompressed, 120 recs)

by branch (count | GiB/member):
                    n        gib
branch
(unexpected)      457  15.097282
hydrology_et       13   0.865173
megan_gamma        33   0.407867
temperature         5   0.358429
other               2   0.197754
radiation_albedo   15   0.185394
megan_emissions    12   0.148315
vegetation          6   0.074158
carbon              5   0.061798
snow                5   0.061798
megan_drivers       2   0.024719

MISSING (requested but absent): 0
UNEXPECTED (in file, not requested): 457
   ['ACTUAL_IMMOB', 'AGNPP', 'ALT', 'ALTMAX', 'ATM_TOPO', 'BAF_CROP', 'BAF_PEATF', 'BCDEP', 'BGNPP', 'BSW', 'BTRAN2', 'CH4PROD', 'CH4_SURF_AERE_SAT', 'CH4_SURF_AERE_UNSAT', 'CH4_SURF_DIFF_SAT', 'CH4_SURF_DIFF_UNSAT', 'CH4_SURF_EBUL_SAT', 'CH4_SURF_EBUL_UNSAT', 'COL_FIRE_CLOSS', 'COL_FIRE_NLOSS', 'CONC_O2_SAT', 'CONC_O2_UNSAT', 'COST_NACTIVE', 'COST_NFIX', 'COST_NRETRANS', 'CPHASE', 'CPOOL', 'CROPPROD1C', 'CROPPROD1C_LOSS', 'CROPPROD1N', 'CROPPROD1N_LOSS', 'CROPSEEDC_DEFICIT', 'CWDC', 'CWDC_LOSS', 'CWDC_vr', 'CWDN', 'CWDN_vr', 'DEADCROOTC', 'DEADCROOTN', 'DEADSTEMC', 'DEADSTEMN', 'DENIT', 'DISPVEGC', 'DISPVEGN', 'DSL', 'DSTDEP', 'DSTFLXT', 'DWT_CONV_CFLUX', 'DWT_CONV_CFLUX_DRIBBLED', 'DWT_CONV_NFLUX', 'DWT_CROPPROD1C_GAIN', 'DWT_CROPPROD1N_GAIN', 'DWT_SEEDN_TO_DEADSTEM', 'DWT_SEEDN_TO_LEAF', 'DWT_SLASH_CFLUX', 'DWT_WOODPRODC_GAIN', 'DWT_WOODPRODN_GAIN', 'DZLAKE', 'DZSOI', 'EFLXBUILD', 'EFLX_DYNBAL', 'EFLX_GRND_LAKE', 'EFLX_LH_TOT_R', 'ER', 'ERRH2O', 'ERRH2OSNO', 'ERRSEB', 'ERRSOI', 'ERRSOL', 'ESAI', 'FAREA_BURNED', 'FCEV', 'FCH4', 'FCH4TOCO2', 'FCH4_DFSAT', 'FCOV', 'FCTR', 'FFIX_TO_SMINN', 'FGEV', 'FGR12', 'FH2OSFC', 'FINUNDATED', 'FIRA_R', 'FIRE_R', 'FPI', 'FPSN', 'FREE_RETRANSN_TO_NPOOL', 'FROOTC', 'FROOTC_ALLOC', 'FROOTC_LOSS', 'FROOTN', 'FSAT', 'FSDSNDLN', 'FSDSVDLN', 'FSDSVILN', 'FSH_G', 'FSH_PRECIP_CONVERSION', 'FSH_R', 'FSH_RUNOFF_ICE_TO_LIQ', 'FSH_TO_COUPLER', 'FSH_V', 'FSM', 'FSNO_EFF', 'FSRNDLN', 'FSRNI', 'FSRVDLN', 'FSRVI', 'FUELC', 'F_DENIT', 'F_N2O_DENIT', 'F_N2O_NIT', 'F_NIT', 'GR', 'GRAINC', 'GRAINC_TO_FOOD', 'GRAINC_TO_SEED', 'GRAINN', 'GROSS_NMIN', 'GSSHA', 'GSSHALN', 'GSSUN', 'GSSUNLN', 'H2OCAN', 'H2OSFC', 'H2OSNO_TOP', 'HEAT_CONTENT1', 'HEAT_FROM_AC', 'HIA', 'HIA_R', 'HIA_U', 'HKSAT', 'HR_vr', 'HUMIDEX', 'HUMIDEX_R', 'HUMIDEX_U', 'ICE_CONTENT1', 'JMX25T', 'Jmx25Z', 'LAKEICEFRAC_SURF', 'LAKEICETHICK', 'LAND_USE_FLUX', 'LEAFC', 'LEAFCN', 'LEAFC_ALLOC', 'LEAFC_CHANGE', 'LEAFC_LOSS', 'LEAFC_TO_LITTER_FUN', 'LEAFN', 'LEAFN_TO_LITTER', 'LEAF_MR', 'LFC2', 'LIQCAN', 'LIQUID_CONTENT1', 'LITFALL', 'LITR1C', 'LITR1C_vr', 'LITR1N', 'LITR1N_vr', 'LITR2C', 'LITR2C_vr', 'LITR2N', 'LITR2N_vr', 'LITR3C', 'LITR3C_vr', 'LITR3N', 'LITR3N_vr', 'LITTERC_HR', 'LITTERC_LOSS', 'LIVECROOTC', 'LIVECROOTN', 'LIVESTEMC', 'LIVESTEMN', 'LNC', 'MEG_2met_styrene', 'MEG_bergamotene_a', 'MEG_bisabolene_b', 'MEG_bornene', 'MEG_butene', 'MEG_camphene', 'MEG_carbon_monoxide', 'MEG_caryophyllene_b', 'MEG_cymene_o', 'MEG_cymene_p', 'MEG_ethane', 'MEG_ethene', 'MEG_farnescene_b', 'MEG_fenchene_a', 'MEG_formic_acid', 'MEG_heptane', 'MEG_hexane', 'MEG_humulene_a', 'MEG_hydrogen_cyanide', 'MEG_ocimene_al', 'MEG_ocimene_c_b', 'MEG_ocimene_t_b', 'MEG_pentane', 'MEG_phellandrene_a', 'MEG_phellandrene_b', 'MEG_propane', 'MEG_propene', 'MEG_sabinene', 'MEG_terpinene_a', 'MEG_terpinene_g', 'MEG_terpinolene', 'MEG_thujene_a', 'MEG_toluene', 'MEG_tricyclene', 'MR', 'NACTIVE', 'NACTIVE_NH4', 'NACTIVE_NO3', 'NAM', 'NAM_NH4', 'NAM_NO3', 'NBP', 'NDEPLOY', 'NDEP_TO_SMINN', 'NECM', 'NECM_NH4', 'NECM_NO3', 'NEM', 'NEP', 'NET_NMIN', 'NFERTILIZATION', 'NFIRE', 'NFIX', 'NNONMYC', 'NNONMYC_NH4', 'NNONMYC_NO3', 'NPASSIVE', 'NPOOL', 'NPP_GROWTH', 'NPP_NACTIVE', 'NPP_NACTIVE_NH4', 'NPP_NACTIVE_NO3', 'NPP_NAM', 'NPP_NAM_NH4', 'NPP_NAM_NO3', 'NPP_NECM', 'NPP_NECM_NH4', 'NPP_NECM_NO3', 'NPP_NFIX', 'NPP_NNONMYC', 'NPP_NNONMYC_NH4', 'NPP_NNONMYC_NO3', 'NPP_NRETRANS', 'NPP_NUPTAKE', 'NRETRANS', 'NRETRANS_REG', 'NRETRANS_SEASON', 'NRETRANS_STRESS', 'NUPTAKE', 'NUPTAKE_NPP_FRACTION', 'OCDEP', 'O_SCALAR', 'PBOT', 'PCH4', 'PCO2', 'PCT_CFT', 'PCT_GLC_MEC', 'PCT_LANDUNIT', 'PFT_FIRE_CLOSS', 'PFT_FIRE_NLOSS', 'PLANT_NDEMAND', 'POTENTIAL_IMMOB', 'POT_F_DENIT', 'POT_F_NIT', 'PSNSHA', 'PSNSHADE_TO_CPOOL', 'PSNSUN', 'PSNSUN_TO_CPOOL', 'Q2M', 'QBOT', 'QCHARGE', 'QDRAI', 'QDRAI_PERCH', 'QDRAI_XS', 'QDRIP', 'QFLOOD', 'QFLX_DEW_GRND', 'QFLX_DEW_SNOW', 'QFLX_ICE_DYNBAL', 'QFLX_LIQ_DYNBAL', 'QFLX_SNOW_DRAIN', 'QFLX_SNOW_DRAIN_ICE', 'QFLX_SUB_SNOW', 'QH2OSFC', 'QICE', 'QICE_FRZ', 'QICE_MELT', 'QINFL', 'QIRRIG', 'QRGWL', 'QRUNOFF_ICE', 'QRUNOFF_ICE_TO_COUPLER', 'QRUNOFF_TO_COUPLER', 'QSNOCPLIQ', 'QSNOEVAP', 'QSNOFRZ', 'QSNOFRZ_ICE', 'QSNOMELT', 'QSNOMELT_ICE', 'QSNO_TEMPUNLOAD', 'QSNO_WINDUNLOAD', 'QSNWCPICE', 'QSOIL_ICE', 'RAIN_FROM_ATM', 'RETRANSN', 'RETRANSN_TO_NPOOL', 'RH2M', 'RR', 'RSSHA', 'RSSUN', 'SABG', 'SABG_PEN', 'SABV', 'SEEDC', 'SEEDN', 'SLASH_HARVESTC', 'SMINN', 'SMINN_TO_NPOOL', 'SMINN_TO_PLANT', 'SMINN_TO_PLANT_FUN', 'SMINN_vr', 'SMIN_NH4', 'SMIN_NH4_vr', 'SMIN_NO3', 'SMIN_NO3_LEACHED', 'SMIN_NO3_RUNOFF', 'SMIN_NO3_vr', 'SMP', 'SNOBCMCL', 'SNOBCMSL', 'SNOCAN', 'SNODSTMCL', 'SNODSTMSL', 'SNOFSRND', 'SNOFSRNI', 'SNOFSRVD', 'SNOFSRVI', 'SNOINTABS', 'SNOOCMCL', 'SNOOCMSL', 'SNOTXMASS', 'SNOUNLOAD', 'SNOW_DEPTH', 'SNOW_FROM_ATM', 'SNOW_PERSISTENCE', 'SNOW_SINKS', 'SNOW_SOURCES', 'SOIL1C', 'SOIL1C_vr', 'SOIL1N', 'SOIL1N_vr', 'SOIL2C', 'SOIL2C_vr', 'SOIL2N', 'SOIL2N_vr', 'SOIL3C', 'SOIL3C_vr', 'SOIL3N', 'SOIL3N_vr', 'SOILC_CHANGE', 'SOILC_HR', 'SOILRESIS', 'SOILWATER_10CM', 'SOMC_FIRE', 'SOM_C_LEACHED', 'SR', 'STORVEGC', 'STORVEGN', 'SUCSAT', 'SUPPLEMENT_TO_SMINN', 'SWBGT', 'SWBGT_R', 'SWBGT_U', 'TAUX', 'TAUY', 'TBOT', 'TBUILD', 'TH2OSFC', 'THBOT', 'TKE1', 'TLAKE', 'TOTCOLC', 'TOTCOLCH4', 'TOTCOLN', 'TOTECOSYSC', 'TOTECOSYSN', 'TOTLITC', 'TOTLITC_1m', 'TOTLITN', 'TOTLITN_1m', 'TOTPFTC', 'TOTPFTN', 'TOTSOILICE', 'TOTSOILLIQ', 'TOTSOMC', 'TOTSOMC_1m', 'TOTSOMN', 'TOTSOMN_1m', 'TOTVEGC', 'TOTVEGN', 'TOT_WOODPRODC', 'TOT_WOODPRODC_LOSS', 'TOT_WOODPRODN', 'TOT_WOODPRODN_LOSS', 'TPU25T', 'TREFMNAV', 'TREFMXAV', 'TSL', 'TSOI_10CM', 'TSOI_ICE', 'TWS', 'T_SCALAR', 'U10', 'U10_DUST', 'URBAN_AC', 'URBAN_HEAT', 'VCMX25T', 'VEGWP', 'VOLR', 'VOLRMCH', 'Vcmx25Z', 'WA', 'WASTEHEAT', 'WATSAT', 'WBT', 'WBT_R', 'WBT_U', 'WOODC', 'WOODC_ALLOC', 'WOODC_LOSS', 'WOOD_HARVESTC', 'WOOD_HARVESTN', 'WTGQ', 'W_SCALAR', 'XSMRPOOL', 'XSMRPOOL_RECOVER', 'ZBOT', 'ZLAKE', 'ZSOI', 'ZWT_CH4_UNSAT', 'ZWT_PERCH', 'area', 'date_written', 'landfrac', 'landmask', 'mcdate', 'mcsec', 'mdcur', 'mscur', 'nbedrock', 'nstep', 'pftmask', 'time_bounds', 'time_written']

,variable,dims,multilevel,level_dim,dtype,shape,mib_per_rec,units,long_name,branch
0,ACTUAL_IMMOB,"time,lat,lon",False,,float64,"1,96,144",0.105469,gN/m^2/s,actual N immobilization,(unexpected)
1,AGNPP,"time,lat,lon",False,,float64,"1,96,144",0.105469,gC/m^2/s,aboveground NPP,(unexpected)
2,ALT,"time,lat,lon",False,,float64,"1,96,144",0.105469,m,current active layer thickness,(unexpected)
3,ALTMAX,"time,lat,lon",False,,float64,"1,96,144",0.105469,m,maximum annual active layer thickness,(unexpected)
4,AR,"time,lat,lon",False,,float64,"1,96,144",0.105469,gC/m^2/s,autotrophic respiration (MR + GR),carbon
5,ATM_TOPO,"time,lat,lon",False,,float64,"1,96,144",0.105469,m,atmospheric surface height,(unexpected)
6,BAF_CROP,"time,lat,lon",False,,float64,"1,96,144",0.105469,proportion/sec,fractional area burned for crop,(unexpected)
7,BAF_PEATF,"time,lat,lon",False,,float64,"1,96,144",0.105469,proportion/sec,fractional area burned in peatland,(unexpected)
8,BCDEP,"time,lat,lon",False,,float64,"1,96,144",0.105469,kg/m^2/s,total BC deposition (dry+wet) from atmosphere,(unexpected)
9,BGNPP,"time,lat,lon",False,,float64,"1,96,144",0.105469,gC/m^2/s,belowground NPP,(unexpected)
10,BSW,"levgrnd,lat,lon",True,levgrnd,float64,"25,96,144",2.636719,unitless,slope of soil water retention curve,(unexpected)
11,BTRAN2,"time,lat,lon",False,,float64,"1,96,144",0.105469,unitless,root zone soil wetness factor,(unexpected)
12,BTRANMN,"time,lat,lon",False,,float64,"1,96,144",0.105469,unitless,daily minimum of transpiration beta factor,megan_drivers
13,CH4PROD,"time,lat,lon",False,,float64,"1,96,144",0.105469,gC/m2/s,Gridcell total production of CH4,(unexpected)
14,CH4_SURF_AERE_SAT,"time,lat,lon",False,,float64,"1,96,144",0.105469,mol/m2/s,aerenchyma surface CH4 flux for inundated area...,(unexpected)
15,CH4_SURF_AERE_UNSAT,"time,lat,lon",False,,float64,"1,96,144",0.105469,mol/m2/s,aerenchyma surface CH4 flux for non-inundated ...,(unexpected)
16,CH4_SURF_DIFF_SAT,"time,lat,lon",False,,float64,"1,96,144",0.105469,mol/m2/s,diffusive surface CH4 flux for inundated / lak...,(unexpected)
17,CH4_SURF_DIFF_UNSAT,"time,lat,lon",False,,float64,"1,96,144",0.105469,mol/m2/s,diffusive surface CH4 flux for non-inundated a...,(unexpected)
18,CH4_SURF_EBUL_SAT,"time,lat,lon",False,,float64,"1,96,144",0.105469,mol/m2/s,ebullition surface CH4 flux for inundated / la...,(unexpected)
19,CH4_SURF_EBUL_UNSAT,"time,lat,lon",False,,float64,"1,96,144",0.105469,mol/m2/s,ebullition surface CH4 flux for non-inundated ...,(unexpected)

## 5 · How to read the report

- **MISSING** = you requested it in `fincl` but it's not in the file → silently dropped (wrong name) or gated by a flag that's off. Investigate before trusting the run.
- **UNEXPECTED** = in the file but not in your whitelist → usually an automatic coordinate/bounds/scalar (`hyam`, `time_bnds`, `date`…), which is fine. Anything else means the tape wasn't as clean as intended (check `empty_htapes`).
- **multilevel** flags vertical/pft/column fields (CAM `lev/ilev`; CLM `levsoi/levgrnd/levsno/natpft`) — the size drivers.